### ISSUE TITLE
Chat score system with badges and ranks

### ISSUE THREAD

**Issue by PokeCat420** [SuperViolinsADS/collectorscorner.github.io#45]
The idea is that cats can earn point by chatting and being active. Ranks and badges can be earned after a certain amount of points. It might be good to not do this based off number of messages but rather time in minutes chatting so spamming is not OP.

Priority level 3

**Comment by SuperViolinsADS** [comment]
Duplicate

**Comment by SuperViolinsADS** [comment]
Duplicate
