### ISSUE TITLE
Add About Us

### ISSUE THREAD

**Issue by PokeCat420** [SuperViolinsADS/collectorscorner.github.io#90]
Using pfps let's add a lil blurb about what each cat does

**Comment by SuperViolinsADS** [comment]
CC: The man behind it all. He’s the site owner, runs the Collecting Community YouTube channel and store, and hosts all the giveaways. His dream of a site that offers everything a collector could want and a fun safe community for collectors lead to him founding the Collecting Community site.


SuperViolinsADS: The site manager and chief debugger and coder, most of the site and it’s features were created from scratch by him and he works tirelessly to implement new features and upgrade existing ones.


Valor Puffball: The head of marketing and visual design he is the driving force behind the CC store and collection page as well as the one responsible for layout design and advertising.

Savin Brass: Head of Customer and Employee relations and article writer, most of what you read on the site has been written by him including the rules.

**Comment by SuperViolinsADS** [comment]
Putting the blurbs here so they don't get lost in discord
